---
- name: update system based on debian
  become: true
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
    upgrade: dist
  when: ansible_facts['os_family'] == 'Debian'

- name: update system based on opensuse
  become: true
  community.general.zypper:
    name: '*'
    state: latest
    update_cache: true
  when: ansible_facts['os_family'] == 'Suse'

- name: update system based on alpine
  become: true
  community.general.apk:
    upgrade: true
    update_cache: true
  when: ansible_facts['os_family'] == 'Alpine'
