---
- name: add export entry
  become: true
  ansible.builtin.lineinfile:
    create: true
    insertafter: EOF
    regexp: "^{{EXPORT_PATH}}.*"
    state: present
    path: /etc/exports
    line: "{{EXPORT_PATH}}\t{{EXPORT_OPTS}}"
  notify:
    - restart nfs service
