---
- name: assert variable
  ansible.builtin.assert:
    that:
      - SUBVOLUME_NAME is defined
      - SUBVOLUME_DEST is defined
      - DEVICE_UUID is defined
    fail_msg: missing variables

- name: Add mount of subvolume to fstab
  become: true
  ansible.posix.mount:
    boot: true
    fstype: btrfs
    opts: "subvol=/{{SUBVOLUME_NAME}},relatime"
    path: "{{SUBVOLUME_DEST}}"
    src: "UUID={{DEVICE_UUID}}"
    state: absent

- name: Create subvolume
  become: true
  community.general.btrfs_subvolume:
    name: "{{SUBVOLUME_NAME}}"
    snapshot_conflict: error
    filesystem_uuid: "{{DEVICE_UUID}}"
    state: absent
